apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basic-ui
  template:
    metadata:
      labels:
        app: basic-ui
    spec:
      restartPolicy: Always
      containers:
      - name: basic-ui
        image: itbacep/basic-ui
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "200m"
            memory: "1Gi"
          limits:
            cpu: "600m"
            memory: "2Gi"
        env:
        - name: API_HOST
          value: https://api.rattarchy.xyz
